name: BlobBuild
version: ${project.version}
main: io.github.anjoismysign.blobbuild.BlobBuild
api-version: 1.17
depend: [ BlobLib ]
authors: [ anjoismysign ]
description: An efficient build protection plugin
commands:
  blobbuild:
    usage: "/blobbuild switchstate"
    aliases: [ bb, build ]